#!/bin/bash

WD=$(dirname `readlink -f ./run`)
cd "$WD"

# build the todo file if nothing has effed up the script.
if [ -x "gen_todo.sh" ]; then
  ./gen_todo.sh
  git add TODO.txt
  git commit -m "-- auto-refresh TODO.txt --"
  git push origin master
fi
git pull origin master
# a push and then a pull might be a bad plan. Time will tell.

listenOn="127.0.0.1"
if [ "$1" ]; then
  listenOn="$1"
fi

port="5000"
if [ "$2" ]; then
  port="$2"
fi

# kill the old process first (if found).
pid=`ps gaxu | grep python3 | grep news_v | grep -v grep | awk '{print $2}'`
if [ "$pid" ]; then
  kill "$pid"
fi

# ya' know. things and stuff.
nohup python3 news_v.py -l "$listenOn" 2>&1 >> news.log &
sleep 1

#refresh the image cache
#using localhost instead of $listenOn because user might specify 0.0.0.0
curl "http://localhost:$port" 2>&1 > /dev/null
