#!/bin/bash

WD=$(dirname `readlink -f ./run`)
cd "$WD"

listenOn="127.0.0.1"
if [ "$1" ]; then
  listenOn="$1"
fi

port="5000"
if [ "$2" ]; then
  port="$2"
fi

# kill the old process first (if found).
pid=`ps gaxu | grep python3 | grep news_v | grep -v grep | awk '{print $2}'`
if [ "$pid" ]; then
  kill "$pid"
fi

# ya' know. things and stuff.
# contrary to my usual style, no quotes around $port because obvious reason is obvious.
# Or, more helpfully, the shell/python should NEVER look at a number and think, "oh, that's two things."
nohup python3 news_v.py -l "$listenOn" -p $port 2>&1 >> news.log &
sleep 1

#refresh the image cache
#using localhost instead of $listenOn because user might specify 0.0.0.0
echo "Updating local image cache. This typically takes 30-40sec depending on CPU and network connectivity."
curl "http://localhost:$port" 2>&1 > /dev/null
